/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.datahpcontroller;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.data;
import DAOImplement.dataimplement;
import java.sql.Connection;
import koneksi.connector;
/**
 *
 * @author isatr
 */
public class Keluar extends javax.swing.JFrame {
    
    dataimplement impldatahp;
    List<data> dp;
    Connection connection;
//    Connector connector = new Connector();
//    String nopol, waktumasuk, waktukeluar;

    /**
     * Creates new form Keluar
     */
    datahpcontroller dc;
    
    public Keluar() {
        connection = connector.connection();
        initComponents();
        dc = new datahpcontroller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfnotiket = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlnopol = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlwmasuk = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlwkeluar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jltotal = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Keluar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jButton1.setText("🏠");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 60, 60));

        jButton2.setText("✖");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 13, 60, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No Tiket");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 79, 37));

        jtfnotiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnotiketActionPerformed(evt);
            }
        });
        getContentPane().add(jtfnotiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, 37));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No Polisi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 79, 37));

        jlnopol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlnopol.setForeground(new java.awt.Color(255, 255, 255));
        jlnopol.setText("-");
        getContentPane().add(jlnopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Waktu Masuk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 37));

        jlwmasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlwmasuk.setForeground(new java.awt.Color(255, 255, 255));
        jlwmasuk.setText("-");
        getContentPane().add(jlwmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, 33));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Waktu Keluar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 37));

        jlwkeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlwkeluar.setForeground(new java.awt.Color(255, 255, 255));
        jlwkeluar.setText("-");
        getContentPane().add(jlwkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, 33));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Biaya");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 285, 79, 37));

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 96, -1));

        jltotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jltotal.setForeground(new java.awt.Color(255, 255, 255));
        jltotal.setText("-");
        getContentPane().add(jltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 285, 150, 33));

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 96, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/parkir5.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 170, 170));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/bgkeluar_1.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new KategoriKendaraan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       dc.update();
       dc.tampilkeluar();
  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    private void jtfnotiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnotiketActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfnotiketActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Keluar().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlnopol;
    private javax.swing.JLabel jltotal;
    private javax.swing.JLabel jlwkeluar;
    private javax.swing.JLabel jlwmasuk;
    private javax.swing.JTextField jtfnotiket;
    // End of variables declaration//GEN-END:variables


    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }
    public JTextField getNo_tiket() {
    return jtfnotiket;    
    }
    
//    public JLabel getNo_pol() {
//    return jlnopol;    
//    }
//
//    public JLabel getjLabel4() {
//        return jlnopol;
//    }

//    public void setjLabel4(JLabel jLabel4) {
//        this.jlnopol = jLabel4;
//    }
//-----------------------------------------------
    public JLabel getJlnopol() {
        return jlnopol;
    }

    public void setJlnopol(String jlnopol) {
        this.jlnopol.setText(jlnopol);
    }
   
    
    public JLabel getJltotal() {
        return jltotal;
    }

    public void setJltotal(JLabel jltotal) {
        this.jltotal = jltotal;
    }

    public JLabel getJlwkeluar() {
        return jlwkeluar;
    }

    public void setJlwkeluar(String jlwkeluar) {
        this.jlwkeluar.setText(jlwkeluar);
    }

    public JLabel getJlwmasuk() {
        return jlwmasuk;
    }

    public void setJlwmasuk(String jlwmasuk) {
        this.jlwmasuk.setText(jlwmasuk);
    }

    public JTextField getJtfnotiket() {
        return jtfnotiket;
    }

    public void setJtfnotiket(String jtfnotiket) {
        this.jtfnotiket.setText(jtfnotiket);
    }
    public void setJtfbiaya(String jltotal) {
        this.jltotal.setText(jltotal);
    }
//   public void setFuser(String fuser) {
//        this.fuser.setText(fuser);
    

    private String getNotiket1() {
    return jtfnotiket.getText();    
    }

}
